name: auto-build list

on:
  push:
    branches: [ main ]

jobs:
  make-list:
    runs-on: ubuntu-latest
    steps:
    - name: "Fetching Repository Contents"
      uses: actions/checkout@main

    # Runs a set of commands using the runners shell
    - name: Update README.md
      run: |
          python parse.py > README.md
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git commit -am "Automated list build"
          git push
